@startuml structure

left to right direction
skinparam linetype ortho

package "LAN / 방화벽 관련 다이어그램" as lan {
    cloud "=172.31.0.1" as gateway_cloud {
        package "Router(gateway)" as router {
            component "Nginx(reverse proxy)" as nginx {
                portin "nginx_in" as nginx_in
                portout "proxy" as proxy
            }
            component "ufw" as ufw {
                component "public" as pub {
                    portin "https(8443)" as https_pub
                    portin "vpn" as vpn_in

                    portout "https(8443)" as https_prv
                    portout "vpn_out" as vpn_out
                }
            }
        }
    }
    cloud "=172.31.0.0/16" as prv_ip {

        package "Server(Ubuntu)" as srv {
            cloud "172.31.1.0/16" as server_ip {
                component "Truenas" as nas {
                    database "shared\n(smb, webdav, ...)" as shared {
                        portin " " as shared_port
                    }
                }
                component "Docker" as docker {
                    component "Dashboard" as dashboard {
                        portin http_dashboard
                    }
                    component "Web-drive\nor service requires disk" as webdrv {
                        portin http_webdrv
                    }

                }
                component "Windows" as win 
            }
        }

        actor "Admin" as admin
    }
    cloud "=192.168.0.0/24" as iot_ip {
        actor "Guest" as guest
        entity "IoT" as iot
    } 
    cloud "VPN_cloud" as vpn_cloud
    note as N1 
        - https는 router의 letsencrypt 이용

        - 게스트 네트워크(192.168.0.0)은 내부 네트워크로 접근 불가
        - inbound는 http / https / vpn handshake 만 허용
        - 이외 protocol은 기본값 차단
    end note
}

node "WAN" as wan {
    actor outside
}

node "VPN" as vpn {
    actor remote
}

https_prv --> nginx_in

https_pub <-l- outside

webdrv -> shared_port

proxy --> http_dashboard
proxy --> http_webdrv

remote --> vpn_in
vpn_out --> vpn_cloud
vpn_cloud ---> prv_ip

' Alignment
wan -[hidden]- ufw
prv_ip -[hidden]right- iot_ip
gateway_cloud -[hidden]---- prv_ip
vpn_cloud -[hidden]down------- gateway_cloud
@enduml