version: "3.8"

services:
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
    volumes:
      - piwigo-config:/config
      - media:/gallery
    restart: unless-stopped
    networks:
      - frontend
      - backend
  piwigo-db:
    image: mysql:latest
    restart: always
    networks:
      - backend
    environment:
      MYSQL_DATABASE: "piwigo"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_ROOT_PASSWORD: "mysql"
    volumes:
      - piwigo-db:/var/lib/mysql
