version: "3.8"

services:
  nginx:
    image: "nginx:latest"
    restart: "always"
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /docker/nginx/http.conf.template:/etc/nginx/templates/http.conf.template
      - /etc/letsencrypt:/etc/letsencrypt
