services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # ports:
    # - 9090:9090
    command: "--config.file=/config/prometheus.yaml"
    volumes:
      - /etc/prometheus:/config:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - backend

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    # default port is 9100
    networks:
      - backend
