version: "3.8"

services:
  nginx-proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "nginx"
    restart: "always"
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html

    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=phoi5675@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:
