services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # ports:
    # - 9090:9090
    command: "--config.file=/config/prometheus.yaml"
    volumes:
      - /etc/prometheus:/config:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - backend
