version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    group_add:
      - "109"
    volumes:
      - media:/media
      - nas:/nas
      - jellyfin-config:/config
      - jellyfin-cache:/cache
    networks:
      - frontend
      - backend
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
