version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: always
    volumes:
      - media:/media
      - nas:/nas
      - jellyfin-config:/config
      - jellyfin-cache:/cache
    networks:
      - frontend
      - backend
