version: "3.8"

services:
  nginx:
    image: "jwilder/nginx-proxy:latest"
    container_name: "nginx"
    restart: "anways"
    networks:
      ext_network:
      default:
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /docker/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
