version: "3.8"

services:
  nginx:
    image: nginx
    container_name: "nginx"
    depends_on:
      - ${dashboard}
      - ${photo}
      - ${cloud}
    networks:
      ext_network:
      default:
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /docker/nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf
