services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # ports:
    # - 9090:9090
    command: "--config.file=/config/prometheus.yaml"
    volumes:
      - /etc/prometheus:/config:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - backend

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
    # default port is 9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    # ports:
    #   - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
      - backend
