volumes:
  jellyfin-cache: null
  jellyfin-config: null
  media:
    driver: local
    driver_opts:
      device: //${TRUENAS_IP}/Photo
      o: username=${SMB_ID},password=${SMB_PWD},rw
      type: cifs
  nas:
    driver: local
    driver_opts:
      device: //${TRUENAS_IP}/NAS
      o: username=${SMB_ID},password=${SMB_PWD},rw
      type: cifs
  music:
    driver: local
    driver_opts:
      device: //${TRUENAS_IP}/NAS/Media/Music
      o: username=${SMB_ID},password=${SMB_PWD},rw
      type: cifs
  npm-data: null
  npm-db: null
  npm-ssl: null
  nextcloud-data: null
  nextcloud-db: null
  navidrome-data: null
