version: "3.8"

# TODO: Add dns server(router) using docker daemon config
networks:
  vlan:
    driver: ipvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: "172.31.0.0/16"
          ip_range: "172.31.2.0/24"
