networks:
  backend: null
  frontend: null
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    networks:
    - frontend
    - backend
    volumes:
    - media:/media
    - jellyfin-config:/config
    - jellyfin-cache:/cache
  nextcloud-app:
    environment:
    - MYSQL_PASSWORD=${NEXTCLOUD_DB_PWD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_HOST=nextcloud-db
    image: nextcloud
    networks:
    - frontend
    - backend
    restart: always
    volumes:
    - nextcloud-data:/var/www/html
  nextcloud-db:
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
    - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_PWD}
    - MYSQL_PASSWORD=${NEXTCLOUD_DB_PWD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    image: mariadb
    networks:
    - backend
    restart: always
    volumes:
    - nextcloud-db:/var/lib/mysql
  npm-app:
    environment:
    - DB_MYSQL_HOST=npm-db
    - DB_MYSQL_PORT=3306
    - DB_MYSQL_USER=npm
    - DB_MYSQL_PASSWORD=${NGINX_DB_PWD}
    - DB_MYSQL_NAME=npm
    image: jc21/nginx-proxy-manager:latest
    networks:
    - frontend
    - backend
    ports:
    - 8080:8080
    - 81:81
    - 8443:8443
    restart: always
    volumes:
    - npm-data:/data
    - npm-ssl:/etc/letsencrypt
  npm-db:
    environment:
    - MYSQL_ROOT_PASSWORD=${NGINX_DB_PWD}
    - MYSQL_DATABASE=npm
    - MYSQL_USER=npm
    - MYSQL_PASSWORD=${NGINX_DB_PWD}
    image: jc21/mariadb-aria:latest
    networks:
    - backend
    restart: always
    volumes:
    - npm-db:/var/lib/mysql
  photoview:
    depends_on:
    - photoview_db
    environment:
    - PHOTOVIEW_DATABASE_DRIVER=mysql
    - PHOTOVIEW_MYSQL_URL=photoview:photosecret@tcp(db)/photoview
    - PHOTOVIEW_LISTEN_IP=photoview
    - PHOTOVIEW_LISTEN_PORT=80
    - PHOTOVIEW_MEDIA_CACHE=/app/cache
    - GODEBUG=asyncpreemptoff=1
    - MAPBOX_TOKEN=${MAP_TOKEN}
    image: viktorstrate/photoview:2
    restart: always
    volumes:
    - photoview_api_cache:/app/cache
    - media:/photos:ro
  photoview_db:
    environment:
    - MYSQL_DATABASE=photoview
    - MYSQL_USER=photoview
    - MYSQL_PASSWORD=photosecret
    - MYSQL_RANDOM_ROOT_PASSWORD=1
    image: mariadb:10.5
    networks:
    - backend
    restart: always
    volumes:
    - photoview_db_data:/var/lib/mysql
version: '3.8'
volumes:
  jellyfin-cache: null
  jellyfin-config: null
  media:
    driver: local
    driver_opts:
      device: //${truenas_ip}/Photo
      o: username=${SMB_ID},password=${SMB_PWD},rw
      type: cifs
  nextcloud-data: null
  nextcloud-db: null
  npm-data: null
  npm-db: null
  npm-ssl: null
  photoview_api_cache: null
  photoview_db_data: null
