version: "3.8"

# TODO: Add dns server(router) using docker daemon config
networks:
  mvlan:
    name: mvlan
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: "172.31.0.0/16"
          gateway: "172.31.0.1"
